name: CI/CD with DockerHub + Trivy

on:
  push:
    branches:
      - main
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout
      - name: Checkout
        uses: actions/checkout@v4

      - name: Scan for Secrets (Gitleaks)
        uses: gitleaks/gitleaks-action@v2
        with:
          args: detect --source . --verbose --redact  

      - name: OWASP Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
         project: "myapp"
         path: "."
         format: "HTML"
         out: "reports"    

      - name: Upload OWASP Report
        uses: actions/upload-artifact@v4
        with:
         name: dependency-check-report
         path: reports   

      # 2. SonarCloud Scan
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        with:
          args: >
            -Dsonar.projectKey=LoveAnbu_devops-github-actions-app
            -Dsonar.organization=loveanbu
            -Dsonar.sources=.
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  

      # 3. Docker login
      - name: Login to DockerHub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # 4. Build image
      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/myapp:${{ github.sha }} .
          docker tag ${{ secrets.DOCKER_USERNAME }}/myapp:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/myapp:latest

      # 5. Trivy scan
      - name: Scan Docker Image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ secrets.DOCKER_USERNAME }}/myapp:latest
          format: table
          severity: CRITICAL
          exit-code: '0'

      # 6. Push
      - name: Push Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/myapp:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/myapp:latest

      # 7. Deploy
      - name: Deploy to Kubernetes
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/devops-github-actions-app
            git pull origin main
            kubectl apply -f k8s/
            kubectl set image deployment/myapp myapp=${{ secrets.DOCKER_USERNAME }}/myapp:${{ github.sha }}
            kubectl rollout status deployment/myapp
